"""
Distributed load and verification tests.
Runs against the fully active Docker Compose environment at http://localhost.
"""

import asyncio
import pytest
import httpx
from datetime import datetime, timezone

BASE_URL = "http://localhost"


@pytest.mark.asyncio
async def test_load_distribution():
    """Verify that requests are balanced across all 3 backend server instances."""
    async with httpx.AsyncClient(base_url=BASE_URL) as client:
        server_ids = set()
        # Nginx uses round-robin load balancing. 15 requests should hit all three servers multiple times.
        for _ in range(15):
            res = await client.get("/health", headers={"Connection": "close"})
            assert res.status_code == 200
            server_id = res.headers.get("X-Server-ID")
            assert server_id in ("1", "2", "3")
            server_ids.add(server_id)

        
        # Verify all 3 servers responded
        assert server_ids == {"1", "2", "3"}, f"Only saw servers: {server_ids}"


@pytest.mark.asyncio
async def test_snowflake_uniqueness():
    """Verify Snowflake generators produce unique short codes without collisions under load."""
    async with httpx.AsyncClient(base_url=BASE_URL) as client:
        # Create 300 short URLs concurrently
        async def shorten_one(i: int):
            return await client.post(
                "/shorten",
                json={"url": f"https://unique-test-{i}.com"}
            )

        tasks = [shorten_one(i) for i in range(300)]
        responses = await asyncio.gather(*tasks)

        codes = []
        for res in responses:
            assert res.status_code == 201
            data = res.json()
            codes.append(data["code"])

        # Check for uniqueness
        assert len(codes) == 300
        assert len(set(codes)) == 300, "Detected duplicate short codes generated by Snowflake!"


@pytest.mark.asyncio
async def test_redirect_and_analytics_sync():
    """Verify shortening -> redirecting -> analytics update flow via the standalone consumer."""
    async with httpx.AsyncClient(base_url=BASE_URL) as client:
        # 1. Shorten a URL
        original_url = "https://dist-test.com/"
        res_shorten = await client.post("/shorten", json={"url": original_url})
        assert res_shorten.status_code == 201
        data = res_shorten.json()
        code = data["code"]

        # 2. Verify initial analytics click count is 0
        res_analytics = await client.get(f"/analytics/{code}")
        assert res_analytics.status_code == 200
        assert res_analytics.json()["clicks"] == 0

        # 3. Redirect multiple times
        # follow_redirects=False because we don't want to load external site
        for _ in range(3):
            res_redirect = await client.get(f"/{code}", follow_redirects=False)
            assert res_redirect.status_code == 302
            assert res_redirect.headers.get("location") == original_url

        # 4. Wait for the click consumer to process the Redis stream and write to Postgres
        # Since it runs every loop iteration, a 2 second wait is plenty
        await asyncio.sleep(2.0)

        # 5. Check analytics again
        res_analytics_final = await client.get(f"/analytics/{code}")
        assert res_analytics_final.status_code == 200
        assert res_analytics_final.json()["clicks"] == 3
